name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install yarn
        run: npm install -g yarn

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Test
        run: xvfb-run -a yarn test
